### ISSUE TITLE
[Add a Play]: Expanding Cards

### ISSUE THREAD

**Issue by atapas** [atapas/react-play#111]
Thank You!

**Comment by Deepak8717** [comment]
What's the Play about? 
Ans - Its the list of striped cards/ collapsed cards displaying on the screen. In order to expand the card just click on any of the strip

What ReactJS concept will be used to create this play?
Ans - In this play i have used useState hook, toggle functionality , component re usability. 
 
Are you willing to take it up for implementation?
Ans - Yes
